server:
  port: 8084
   
spring:
 application:
    name: API-GATEWAY
    
 cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE  
          predicates:
            - Paths=/users/**
            
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Paths=/hotels/**
            
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE  
          predicates:
            - Paths=/ratings/**        